#!/bin/sh
# tagr
################################################
VERSION=0.1.0

whichMethod=$1
tagName=$2
IFS=$'\n'

index_file=~/.tagr/.tagr.tmp
index_file_deduped=~/.tagr/.tagr
index_file_dir=$(dirname $index_file)
indexing_dir=~/


spinner() {
  local spin="\\|/-"
  local i=0
  tput civis
  while kill -0 "$1" 2>/dev/null; do
    i=$(( (i+1) %4 ))
    printf "\b%s" "${spin:$i:1}"
    sleep 0.07
  done
  tput cnorm
}


function init() {
  # create directory
  mkdir -p "$index_file_dir"

  # create file
  touch $index_file
}


function dedupe() {
  sort $index_file | uniq > $index_file_deduped
}


function index() {
  # empty index file
  > $index_file

  # reindex
  (for i in $( tag -RNtg $indexing_dir); do
    for j in $( tag -f "$i" ); do
      echo "$i=$j" >> $index_file
    done
  done) &
  spinner $!

  dedupe
}


function echo_lines() {
  while read p; do
    echo $p
  done < "$index_file_deduped"
}


function search() {
  cd $(echo_lines|fzf|sed "s/.*=//")
}


function add_tag() {
  command tag -a "$1" .
  index &>/dev/null &
}

function remove_tag() {
  command tag -r "$1" .
  index &>/dev/null &
}

function list_tag() {
  command tag -RNtg $indexing_dir
}

# Determining Which Method To Call Based On Command Line Arguments
case $whichMethod in
  init  ) init ;;
  index ) index ;;
  list  ) list_tag ;;
  add   ) add_tag "$2" ;;
  remove) remove_tag "$2" ;;
  *     ) search ;;
esac


