#!/bin/sh
# tagr
################################################
VERSION=0.1.0

whichMethod=$1
IFS=$'\n'

INDEX_FILE=~/.tagr/.tagr
INDEX=~/.tagr/.index
INDEX_DIR=$(dirname $INDEX_FILE)
INDEXING_DIR=~/


spinner() {
  local spin="\\|/-"
  local i=0
  tput civis
  while kill -0 "$1" 2>/dev/null; do
    i=$(( (i+1) %4 ))
    printf "\b%s" "${spin:$i:1}"
    sleep 0.07
  done
  tput cnorm
}


function init() {
  # create directory
  mkdir -p "$INDEX_DIR"

  # create file
  touch $INDEX_FILE
}


function dedupe() {
  sort $INDEX_FILE | uniq > $INDEX
}


function index() {
  # empty index file
  # echo "" > $INDEX_FILE

  # reindex
  (for i in $( tag -RNtg ); do
    for j in $( tag -f "$i" ); do
      echo "$i=$j" >> $INDEX_FILE
    done
  done) &
  # show spinner while indexing
  spinner $!
  # dedupe results
  dedupe
}


function echo_lines() {
  while read p; do
    echo $p
  done < "$INDEX"
}


function search() {
  cd $(echo_lines|fzf|sed "s/.*=//")
}


# Determining Which Method To Call Based On Command Line Arguments
case $whichMethod in
  index ) index ;;
  * ) search ;;
esac


